namespace Piped.PipedApi {
    public class Subtitle : Object {
        public string url { get; set; }
        public string mimeType { get; set; }
        public string name { get; set; }
        public string code { get; set; }

        public bool autoGenerated { get; set; }
    }
}
